USE [master]
GO
/****** Object:  Database [nvz_profiler]    Script Date: 9/23/2025 12:04:47 PM ******/
CREATE DATABASE [nvz_profiler]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nvz_profiler', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.NVZMSSQL\MSSQL\DATA\nvz_profiler.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'nvz_profiler_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.NVZMSSQL\MSSQL\DATA\nvz_profiler_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [nvz_profiler] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nvz_profiler].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [nvz_profiler] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [nvz_profiler] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [nvz_profiler] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [nvz_profiler] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [nvz_profiler] SET ARITHABORT OFF 
GO
ALTER DATABASE [nvz_profiler] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [nvz_profiler] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [nvz_profiler] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [nvz_profiler] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [nvz_profiler] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [nvz_profiler] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [nvz_profiler] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [nvz_profiler] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [nvz_profiler] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [nvz_profiler] SET  ENABLE_BROKER 
GO
ALTER DATABASE [nvz_profiler] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [nvz_profiler] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [nvz_profiler] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [nvz_profiler] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [nvz_profiler] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [nvz_profiler] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [nvz_profiler] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [nvz_profiler] SET RECOVERY FULL 
GO
ALTER DATABASE [nvz_profiler] SET  MULTI_USER 
GO
ALTER DATABASE [nvz_profiler] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [nvz_profiler] SET DB_CHAINING OFF 
GO
ALTER DATABASE [nvz_profiler] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [nvz_profiler] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [nvz_profiler] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [nvz_profiler] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'nvz_profiler', N'ON'
GO
ALTER DATABASE [nvz_profiler] SET QUERY_STORE = ON
GO
ALTER DATABASE [nvz_profiler] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
ALTER DATABASE [nvz_profiler] SET  READ_WRITE 
GO
